#!/usr/bin/env python3
"""
ptx_parser.py — Parse NVIDIA PTX assembly into structured kernel representations.

Parses kernel.ptx (generated by nvcc -ptx) and extracts:
  - Kernel names and parameters
  - Register declarations
  - Instructions (including inline asm blocks)
  - Labels and control flow

Output: list of KernelInfo objects, one per .entry function.
"""

import re
import sys
from dataclasses import dataclass, field


@dataclass
class PTXParam:
    name: str       # e.g. "vec_add_i16_param_0"
    type: str       # e.g. "u64", "u32"


@dataclass
class PTXInstruction:
    """A single parsed PTX instruction."""
    op: str              # e.g. "add.s16", "ld.global.nc.u16", "fma.rn.bf16"
    operands: list       # list of operand strings
    predicate: str = ""  # e.g. "@%p1" or ""
    is_label: bool = False
    label: str = ""      # e.g. "$L__BB0_2"
    raw: str = ""        # original text for debugging


@dataclass
class KernelInfo:
    name: str
    params: list = field(default_factory=list)        # list of PTXParam
    reg_decls: dict = field(default_factory=dict)      # type -> count
    instructions: list = field(default_factory=list)   # list of PTXInstruction


def parse_ptx(text):
    """Parse PTX text into a list of KernelInfo objects."""
    kernels = []
    lines = text.split('\n')
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # Detect kernel entry
        if line.startswith('.visible .entry'):
            kernel, i = _parse_kernel(lines, i)
            kernels.append(kernel)
        else:
            i += 1

    return kernels


def _parse_kernel(lines, start):
    """Parse a single kernel function starting at the .visible .entry line."""
    # Extract kernel name
    m = re.match(r'\.visible\s+\.entry\s+(\w+)\s*\(', lines[start].strip())
    kernel = KernelInfo(name=m.group(1))

    i = start + 1

    # Parse parameters until ')'
    while i < len(lines):
        line = lines[i].strip()
        param_match = re.match(r'\.param\s+\.(\w+)\s+(\w+)', line)
        if param_match:
            kernel.params.append(PTXParam(
                type=param_match.group(1),
                name=param_match.group(2),
            ))
        if ')' in line:
            i += 1
            break
        i += 1

    # Skip to opening brace
    while i < len(lines) and '{' not in lines[i]:
        i += 1
    i += 1  # skip '{'

    # Parse body until closing brace
    in_inline_asm = False
    inline_asm_lines = []

    while i < len(lines):
        line = lines[i].strip()

        # Check for closing brace of kernel
        if line == '}' and not in_inline_asm:
            i += 1
            break

        # Register declarations
        reg_match = re.match(r'\.reg\s+\.(\w+)\s+%(\w+)<(\d+)>', line)
        if reg_match:
            kernel.reg_decls[reg_match.group(1)] = int(reg_match.group(3))
            i += 1
            continue

        # Inline asm detection
        if '// begin inline asm' in line:
            in_inline_asm = True
            inline_asm_lines = []
            i += 1
            continue
        if '// end inline asm' in line:
            in_inline_asm = False
            _parse_inline_asm(inline_asm_lines, kernel.instructions)
            i += 1
            continue
        if in_inline_asm:
            inline_asm_lines.append(line)
            i += 1
            continue

        # Skip empty lines and comments
        if not line or line.startswith('//'):
            i += 1
            continue

        # Parse instruction
        instr = _parse_instruction(line)
        if instr:
            kernel.instructions.append(instr)

        i += 1

    return kernel, i


def _parse_inline_asm(lines, instr_list):
    """Parse inline asm block and extract meaningful instructions."""
    for line in lines:
        line = line.strip().strip('{}').strip()
        if not line:
            continue

        # Split multiple instructions on ';'
        for part in line.split(';'):
            part = part.strip()
            if not part:
                continue
            # Skip local reg declarations inside inline asm
            if part.startswith('.reg'):
                continue

            instr = _parse_instruction(part + ';')
            if instr:
                instr_list.append(instr)


def _parse_instruction(line):
    """Parse a single PTX instruction line into a PTXInstruction."""
    line = line.strip().rstrip(';').strip()
    if not line:
        return None

    # Label (e.g., "$L__BB0_2:")
    if line.startswith('$') and line.endswith(':'):
        return PTXInstruction(
            op='label', operands=[], is_label=True,
            label=line[:-1], raw=line
        )

    # Predicated instruction (e.g., "@%p1 bra $L__BB0_2")
    predicate = ""
    if line.startswith('@'):
        m = re.match(r'(@\S+)\s+(.*)', line)
        if m:
            predicate = m.group(1)
            line = m.group(2).strip()

    # Split op and operands
    parts = line.split(None, 1)
    if not parts:
        return None

    op = parts[0]
    operands = []

    if len(parts) > 1:
        operand_str = parts[1]
        # Split by comma, but respect brackets []
        operands = _split_operands(operand_str)

    return PTXInstruction(
        op=op, operands=operands, predicate=predicate,
        raw=line
    )


def _split_operands(s):
    """Split operand string by commas, respecting brackets."""
    operands = []
    depth = 0
    current = []
    for ch in s:
        if ch == '[':
            depth += 1
        elif ch == ']':
            depth -= 1
        elif ch == ',' and depth == 0:
            operands.append(''.join(current).strip())
            current = []
            continue
        current.append(ch)
    if current:
        operands.append(''.join(current).strip())
    return operands


def print_kernel_summary(kernel):
    """Print a human-readable summary of a parsed kernel."""
    print(f"\nKernel: {kernel.name}")
    print(f"  Params ({len(kernel.params)}):")
    for p in kernel.params:
        print(f"    .{p.type} {p.name}")
    print(f"  Registers: {kernel.reg_decls}")
    print(f"  Instructions ({len(kernel.instructions)}):")
    for instr in kernel.instructions:
        if instr.is_label:
            print(f"    {instr.label}:")
        else:
            pred = f"{instr.predicate} " if instr.predicate else ""
            ops = ", ".join(instr.operands)
            print(f"    {pred}{instr.op}  {ops}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python ptx_parser.py input.ptx")
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        text = f.read()

    kernels = parse_ptx(text)
    print(f"Parsed {len(kernels)} kernels from {sys.argv[1]}")

    for k in kernels:
        print_kernel_summary(k)
