// tb_ids_generic.v -- Generic GPU testbench for IDS MLP (11->16->8->2)
//
// Uses $readmemh to load kernel and data, reads expected outputs from
// a separate expected-values hex file generated by ids_data_generator.py.
//
// Expected-values file format: one 64-bit hex word per line for
// DMEM addresses 203-218 (L1), 355-362 (L2), 381-382 (L3) = 26 words.
//
// Usage:
//   # Generate expected hex:
//   python toolchains/gpu/ids_data_generator.py [--test] -o programs/gpu/data_ids.hex
//   python toolchains/gpu/ids_gen_expected_hex.py programs/gpu/data_ids_expected.txt \
//          -o programs/gpu/expected_ids.hex
//
//   # Compile and run:
//   iverilog -g2001 -I include -I src/gpu -o tb_ids_gen \
//     src/gpu/*.v tb/tb_ids_generic.v && vvp tb_ids_gen
//
// Or override file paths via plusargs:
//   vvp tb_ids_gen +IMEM=path/to/kernel.hex +DMEM=path/to/data.hex

`timescale 1ns / 1ps

module tb_ids_generic;

    parameter CLK_PERIOD  = 8;
    parameter IMEM_WORDS  = 211;
    parameter DMEM_WORDS  = 383;
    parameter MAX_CYCLES  = 10000;

    // Layer output addresses
    parameter H1_BASE  = 203;
    parameter H1_COUNT = 16;
    parameter H2_BASE  = 355;
    parameter H2_COUNT = 8;
    parameter OUT_BASE = 381;
    parameter OUT_COUNT = 2;

    reg clk, rst;
    always #(CLK_PERIOD/2) clk = ~clk;

    reg  [9:0]  ext_imem_addr;
    reg         ext_imem_wr_en;
    reg  [31:0] ext_imem_wr_data;
    wire [31:0] ext_imem_rd_data;
    reg  [9:0]  ext_dmem_addr;
    reg         ext_dmem_wr_en;
    reg  [63:0] ext_dmem_wr_data;
    wire [63:0] ext_dmem_rd_data;
    wire        kernel_done;

    gpu_top uut (
        .clk(clk), .rst(rst),
        .thread_id(32'd0), .block_id(32'd0), .block_dim(32'd1),
        .kernel_done(kernel_done),
        .ext_imem_addr(ext_imem_addr),
        .ext_imem_wr_en(ext_imem_wr_en),
        .ext_imem_wr_data(ext_imem_wr_data),
        .ext_imem_rd_data(ext_imem_rd_data),
        .ext_dmem_addr(ext_dmem_addr),
        .ext_dmem_wr_en(ext_dmem_wr_en),
        .ext_dmem_wr_data(ext_dmem_wr_data),
        .ext_dmem_rd_data(ext_dmem_rd_data)
    );

    reg [31:0] imem_file [0:1023];
    reg [63:0] dmem_file [0:1023];
    // Expected values: 16 (L1) + 8 (L2) + 2 (L3) = 26 words
    reg [63:0] expected  [0:25];

    integer i, cycle_count, pass_count, fail_count;
    reg [63:0] actual;

    task write_imem;
        input [9:0] addr; input [31:0] data;
        begin
            @(posedge clk);
            ext_imem_addr = addr; ext_imem_wr_data = data; ext_imem_wr_en = 1;
            @(posedge clk);
            ext_imem_wr_en = 0;
        end
    endtask

    task write_dmem;
        input [9:0] addr; input [63:0] data;
        begin
            @(posedge clk);
            ext_dmem_addr = addr; ext_dmem_wr_data = data; ext_dmem_wr_en = 1;
            @(posedge clk);
            ext_dmem_wr_en = 0;
        end
    endtask

    task read_dmem;
        input [9:0] addr; output [63:0] data;
        begin
            @(posedge clk);
            ext_dmem_addr = addr; ext_dmem_wr_en = 0;
            @(posedge clk);
            data = ext_dmem_rd_data;
        end
    endtask

    task check_dmem;
        input [9:0] addr; input [63:0] exp; input [8*8-1:0] label;
        begin
            read_dmem(addr, actual);
            if (actual === exp) begin
                $display("  PASS  DMEM[%0d] %s = 0x%016h", addr, label, actual);
                pass_count = pass_count + 1;
            end else begin
                $display("  FAIL  DMEM[%0d] %s = 0x%016h (exp 0x%016h)",
                         addr, label, actual, exp);
                fail_count = fail_count + 1;
            end
        end
    endtask

    initial begin
        for (i = 0; i < 1024; i = i + 1) begin
            imem_file[i] = 32'h0;
            dmem_file[i] = 64'h0;
        end
        for (i = 0; i < 26; i = i + 1) expected[i] = 64'h0;

        $readmemh("programs/gpu/ann_ids_11_16_8_2.hex", imem_file);
        $readmemh("programs/gpu/data_ids_11_16_8_2.hex", dmem_file);
        $readmemh("programs/gpu/expected_ids.hex", expected);

        clk = 0; rst = 1;
        ext_imem_wr_en = 0; ext_dmem_wr_en = 0;
        ext_imem_addr = 0;  ext_dmem_addr = 0;
        ext_imem_wr_data = 0; ext_dmem_wr_data = 0;
        pass_count = 0; fail_count = 0;
        repeat (5) @(posedge clk);

        $display("========================================");
        $display("IDS MLP Generic Test");
        $display("========================================");

        // Load IMEM
        for (i = 0; i < IMEM_WORDS; i = i + 1) write_imem(i[9:0], imem_file[i]);
        // Load DMEM
        for (i = 0; i < DMEM_WORDS; i = i + 1) write_dmem(i[9:0], dmem_file[i]);

        // Run kernel
        repeat (2) @(posedge clk);
        rst = 0;
        cycle_count = 0;
        while (!kernel_done && cycle_count < MAX_CYCLES) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end
        rst = 1;
        repeat (2) @(posedge clk);

        if (cycle_count >= MAX_CYCLES)
            $display("TIMEOUT after %0d cycles", MAX_CYCLES);
        else
            $display("Halted after %0d cycles", cycle_count);

        // Check Layer 1
        $display("\n--- Layer 1 (h1[0..15]) ---");
        for (i = 0; i < H1_COUNT; i = i + 1)
            check_dmem(H1_BASE + i, expected[i], "h1");

        // Check Layer 2
        $display("\n--- Layer 2 (h2[0..7]) ---");
        for (i = 0; i < H2_COUNT; i = i + 1)
            check_dmem(H2_BASE + i, expected[H1_COUNT + i], "h2");

        // Check Layer 3
        $display("\n--- Layer 3 (out[0..1]) ---");
        for (i = 0; i < OUT_COUNT; i = i + 1)
            check_dmem(OUT_BASE + i, expected[H1_COUNT + H2_COUNT + i], "out");

        $display("\n========================================");
        $display("%0d PASS, %0d FAIL", pass_count, fail_count);
        if (fail_count == 0) $display("*** ALL TESTS PASSED ***");
        else                 $display("*** SOME TESTS FAILED ***");
        $display("========================================");
        #100; $finish;
    end

endmodule
